# Docker Compose configuration for a Django application with MySQL database

services:
  db:
    image: mysql:8.3
    container_name: messaging_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging_web
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    # Development: runserver
    command: >
      sh -c "python manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    # Production: gunicorn
    # command: >
    #   sh -c "python manage.py migrate &&
    #          gunicorn messaging_app.wsgi:application --bind 0.0.0.0:8000"

volumes:
  db_data:
