pipeline {
    agent any

    tools {
        python 'Python3' // Ensure this is configured in Jenkins global tool config
    }

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', // specify branch
                    credentialsId: 'github-creds',
                    url: 'https://github.com/sakachris/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv $VENV_DIR
                    source $VENV_DIR/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source $VENV_DIR/bin/activate
                    cd messaging_app
                    pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'messaging_app/report.xml', fingerprint: true
        }
    }
}
