# kubeservice.yaml
apiVersion: v1
kind: Service
metadata:
  name: messaging-blue-green
spec:
  selector:
    app: messaging
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP